spring.application.name=backendApplication
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}:5432/springdb
spring.datasource.username=postgres
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.root=info

## To Avoid conflict between @EnableRedisRepositories and @EnableJpaRepositories
## when using both JPA and Redis repositories in the same application.
## This property allows bean definition overriding, which is necessary when both
## repositories are defined in the same application context.
#spring.main.allow-bean-definition-overriding=true

jwt.secret = ${JWT_SECRET}

##Spring Security
spring.security.user.name=admin
spring.security.user.password=123456789

## Redis Configuration
spring.redis.host=${REDIS_HOST}
spring.redis.port=6379
#spring.redis.password=redis
## Redis Cache Configuration
# spring.cache.cache-names=cache1,cache2
# spring.cache.redis.time-to-live=60000
spring.cache.type=redis
spring.cache.redis.cache-null-values=true
